// Thin fetch wrapper. No axios: the app makes six calls and none of them need an
// interceptor stack.

const KEY_STORAGE = 'snip.apiKey';

/**
 * The API key is a capability token. It is generated by the server on demand and kept
 * in localStorage; there are no accounts. That means clearing site data loses access to
 * managing your links, which is a real limitation and is stated in the README rather
 * than hidden.
 */
export function getApiKey() {
  return localStorage.getItem(KEY_STORAGE);
}

export function setApiKey(key) {
  localStorage.setItem(KEY_STORAGE, key);
}

export async function ensureApiKey() {
  const existing = getApiKey();
  if (existing) return existing;
  const res = await fetch('/api/keys', { method: 'POST' });
  if (!res.ok) throw new ApiError('Could not mint an API key', res.status, null);
  const { apiKey } = await res.json();
  setApiKey(apiKey);
  return apiKey;
}

export class ApiError extends Error {
  constructor(message, status, body) {
    super(message);
    this.status = status;
    this.body = body;
    this.retryAfterSeconds = body?.retryAfterSeconds ?? null;
  }
}

async function request(path, { method = 'GET', body, withKey = true } = {}) {
  const headers = {};
  if (body !== undefined) headers['Content-Type'] = 'application/json';
  if (withKey) {
    const key = await ensureApiKey();
    headers['X-API-Key'] = key;
  }

  const res = await fetch(path, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  if (res.status === 204) return null;

  let parsed = null;
  const text = await res.text();
  if (text) {
    try {
      parsed = JSON.parse(text);
    } catch {
      parsed = { message: text };
    }
  }

  if (!res.ok) {
    // 429 gets a first-class message. Surfacing the rate limiter in the UI is what
    // proves it is wired end to end rather than being a filter nobody ever hits.
    if (res.status === 429) {
      const secs = parsed?.retryAfterSeconds ?? Number(res.headers.get('Retry-After')) ?? 1;
      throw new ApiError(`Rate limited. Try again in ${secs}s.`, 429, { retryAfterSeconds: secs });
    }
    throw new ApiError(parsed?.message || `Request failed (${res.status})`, res.status, parsed);
  }

  return {
    data: parsed,
    rateLimit: {
      limit: Number(res.headers.get('X-RateLimit-Limit')) || null,
      remaining: Number(res.headers.get('X-RateLimit-Remaining')) || 0,
      scope: res.headers.get('X-RateLimit-Scope'),
    },
  };
}

export const api = {
  createLink: (payload) => request('/api/links', { method: 'POST', body: payload }),
  listLinks: (page = 0, size = 50) => request(`/api/links?page=${page}&size=${size}`),
  updateLink: (code, payload) => request(`/api/links/${code}`, { method: 'PATCH', body: payload }),
  deleteLink: (code) => request(`/api/links/${code}`, { method: 'DELETE' }),
  analytics: (code, days = 30) => request(`/api/links/${code}/analytics?days=${days}`),
  status: () => request('/api/status', { withKey: false }),
  qrUrl: (code, size = 220) => `/api/links/${code}/qr?size=${size}`,
};
